spring:
  application:
    name: at0m-available-quantity-api
  data:
    mongodb:
      auto-index-creation: true
      database: at0m
      port: 27017
      host: localhost

server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  enabled: true

ribbon:
  listOfServers: http://localhost:8761/
  eureka:
    enabled: true

feign:
  client:
    config:
      default:
        logger-level: full
        read-timeout: 5000
        connect-timeout: 5000